[tool.poetry]
name = "pysurrealdb"
version = "0.1.0"
description = "A library to connect to SurrealDB."
readme = "README.md"
authors = ["Aurelion314"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"